<?php
require_once(dirname(__FILE__).'/../../../../init_new.php');
require_once(XOOPS_TU_ROOT_PATH.'/modules/avatars/class/AvatarsProvider.php');

use Xoops\Core\Service\Manager;
use Xoops\Core\Service\Provider;
use Xoops\Core\Kernel\Handlers\XoopsUser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-07-30 at 19:01:39.
 */

/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class ProviderTest extends \PHPUnit_Framework_TestCase
{
    protected $service = 'Avatar';

    /**
     * @var Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $manager = Manager::getInstance();
        $this->object = new Provider($manager, $this->service);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xoops\Core\Service\Provider::getProviderMode
     */
    public function testGetProviderMode()
    {
        $instance = $this->object;

        $result = $instance->getProviderMode();
        $this->assertSame(Manager::MODE_EXCLUSIVE, $result);
    }

    /**
     * @covers Xoops\Core\Service\Provider::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {
        // see testSortProviders
    }

    /**
     * @covers Xoops\Core\Service\Provider::getRegistered
     */
    public function testGetRegistered()
    {
        // see testSortProviders
    }

    /**
     * @covers Xoops\Core\Service\Provider::sortProviders
     */
    public function testSortProviders()
    {
        $instance = $this->object;

        $provider1 = new AvatarsProvider();
        $provider1->setPriority(10);
        $instance->register($provider1);

        $provider2 = new AvatarsProvider();
        $provider2->setPriority(5);
        $instance->register($provider2);

        $instance->sortProviders();

        $result = $instance->getRegistered();
        $this->assertSame($provider2, $result[0]);
        $this->assertSame(5, $result[0]->getPriority());
        $this->assertSame($provider1, $result[1]);
        $this->assertSame(10, $result[1]->getPriority());
    }

    /**
     * @covers Xoops\Core\Service\Provider::isAvailable
     * @todo   Implement testIsAvailable().
     */
    public function testIsAvailable()
    {
        $instance = $this->object;

        $result = $instance->isAvailable();
        $this->assertTrue($result);
    }

    /**
     * @covers Xoops\Core\Service\Provider::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        $instance = $this->object;

        $provider = new AvatarsProvider();
        $instance->register($provider);

        $user = new XoopsUser();
        $result = $instance->getAvatarEditUrl($user);
        $this->assertInstanceOf('\Xoops\Core\Service\Response',$result);
        $this->assertTrue($result->isSuccess());

        $result = $instance->getAvatarUrl($provider);
        $this->assertInstanceOf('\Xoops\Core\Service\Response',$result);
        $this->assertFalse($result->isSuccess());
    }

    /**
     * @covers Xoops\Core\Service\Provider::__callStatic
     * @todo   Implement test__callStatic().
     */
    public function test__callStatic()
    {
        $result = Provider::staticDummyMethod();
        $this->assertTrue(is_null($result));
    }
}
