tables:
    banners_banner:
        options: {  }
        columns:
            banner_bid:
                name: banner_bid
                type: smallint
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: true
                columnDefinition: null
                comment: ''
            banner_cid:
                name: banner_cid
                type: boolean
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_imptotal:
                name: banner_imptotal
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_impmade:
                name: banner_impmade
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_clicks:
                name: banner_clicks
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_imageurl:
                name: banner_imageurl
                type: string
                default: ''
                notnull: true
                length: 255
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_clickurl:
                name: banner_clickurl
                type: string
                default: ''
                notnull: true
                length: 255
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_datestart:
                name: banner_datestart
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_dateend:
                name: banner_dateend
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_htmlbanner:
                name: banner_htmlbanner
                type: boolean
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_htmlcode:
                name: banner_htmlcode
                type: text
                default: null
                notnull: false
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: ''
            banner_status:
                name: banner_status
                type: boolean
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: ''
        indexes:
            PRIMARY:
                name: PRIMARY
                columns: [banner_bid]
                unique: true
                primary: true
            banner_cid:
                name: banner_cid
                columns: [banner_cid]
                unique: false
                primary: false
            banner_bidcid:
                name: banner_bidcid
                columns: [banner_bid, banner_cid]
                unique: false
                primary: false
    banners_bannerclient:
        options: {  }
        columns:
            bannerclient_cid:
                name: bannerclient_cid
                type: smallint
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: true
                columnDefinition: null
                comment: ''
            bannerclient_uid:
                name: bannerclient_uid
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: false
                columnDefinition: null
                comment: ''
            bannerclient_name:
                name: bannerclient_name
                type: string
                default: ''
                notnull: true
                length: 60
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: ''
            bannerclient_extrainfo:
                name: bannerclient_extrainfo
                type: text
                default: null
                notnull: false
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: ''
        indexes:
            PRIMARY:
                name: PRIMARY
                columns: [bannerclient_cid]
                unique: true
                primary: true
            bannerclient_name:
                name: bannerclient_name
                columns: [bannerclient_name]
                unique: false
                primary: false
