<?php
namespace Xoops\Core\Locale\Resource;

use Xoops\Core\Locale\Resource;

require_once(dirname(__FILE__).'/../../../../../init_new.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-16 at 13:57:33.
 */
class PoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Po
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Po;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testContracts()
    {
        $this->object = new Po('fr_FR', 'system', 'url');
        $this->assertInstanceOf('\Xoops\Core\Locale\Resource', $this->object);
        $this->assertInstanceOf('\Xoops\Core\Locale\Resource\Po', $this->object);
    }

    public function test__construct()
    {
        $this->object = new Po('fr_FR', 'system', 'url');
        $this->assertEquals(Resource::TYPE_PO, $this->object->type);
        $this->assertEquals('fr_FR', $this->object->locale);
        $this->assertEquals('system', $this->object->domain);
        $this->assertEquals('url', $this->object->uri);
        $this->assertEquals(null, $this->object->subdomain);
    }
}
