<?php
namespace Xoops\Core\Handler\Scheme;

use Xoops\Core\Handler\Factory;

require_once __DIR__ . '/../../../../../init_new.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-22 at 18:11:45.
 */
class SchemeInterfaceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Kernel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMock('\Xoops\Core\Handler\Scheme\SchemeInterface');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testContracts()
    {
        $this->assertInstanceOf('\Xoops\Core\Handler\Scheme\SchemeInterface', $this->object);
    }

    /**
     * @covers Xoops\Core\Handler\Scheme\SchemeInterface::build
     */
    public function testBuild()
    {
        $spec = Factory::getInstance()->newSpec();
        $this->assertNull($this->object->build($spec));
    }
}
