<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*/

/**
 * System menu
 *
 * @copyright   The XOOPS Project http://sourceforge.net/projects/xoops/
 * @license     GNU GPL 2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
 * @package     system
 * @author      Kazumi Ono (AKA onokazu)
 * @version     $Id$
 */

defined('XOOPS_ROOT_PATH') or die('Restricted access');

/*
 General settings
 */
$modversion['name'] = SystemLocale::MODULE_NAME;
$modversion['description'] = SystemLocale::MODULE_DESCRIPTION;
$modversion['version'] = 2.10;
$modversion['author'] = 'Andricq Nicolas,Cointin Maxime,Mage Gregory';
$modversion['nickname'] = 'MusS,Kraven30,Mage';
$modversion['credits'] = 'The XOOPS Project';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = 'www.gnu.org/licenses/gpl-2.0.html/';
$modversion['official'] = 1;
$modversion['help'] = 'system.html';
$modversion['image'] = 'images/logo.png';
$modversion['dirname'] = 'system';

/*
 Settings for configs
*/
$modversion['release_date'] = '2011/12/20';
$modversion['module_website_url'] = 'http://www.xoops.org/';
$modversion['module_website_name'] = 'XOOPS';
$modversion['module_status'] = 'ALPHA';
$modversion['min_php'] = '5.3';
$modversion['min_xoops'] = '2.6.0';
$modversion['min_db'] = array('mysql' => '5.0.7', 'mysqli' => '5.0.7');

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin.php';
$modversion['adminmenu'] = 'menu.php';

$modversion['onUpdate'] = 'include/update.php';
$modversion['onInstall'] = 'include/install.php';

// JQuery
$modversion['jquery'] = 1;

// Mysql file
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)

//todo, are we using all these tables?
$i = 1;
$modversion['tables'][$i] = "block_module_link";
$i++;
$modversion['tables'][$i] = "config";
$i++;
$modversion['tables'][$i] = "configoption";
$i++;
$modversion['tables'][$i] = "groups";
$i++;
$modversion['tables'][$i] = "group_permission";
$i++;
$modversion['tables'][$i] = "groups_users_link";
$i++;
$modversion['tables'][$i] = "imgset";
$i++;
$modversion['tables'][$i] = "imgset_tplset_link";
$i++;
$modversion['tables'][$i] = "imgsetimg";
$i++;
$modversion['tables'][$i] = "modules";
$i++;
$modversion['tables'][$i] = "newblocks";
$i++;
$modversion['tables'][$i] = "online";
$i++;
$modversion['tables'][$i] = "priv_msgs";
$i++;
$modversion['tables'][$i] = "ranks";
$i++;
$modversion['tables'][$i] = "session";
$i++;
$modversion['tables'][$i] = "tplset";
$i++;
$modversion['tables'][$i] = "tplfile";
$i++;
$modversion['tables'][$i] = "tplsource";
$i++;
$modversion['tables'][$i] = "users";
$i++;
$modversion['tables'][$i] = "cache_model";

// Admin Templates
// Blocks
$i = 0;
$modversion['blocks'][$i]['file'] = 'user.php';
$modversion['blocks'][$i]['name'] = SystemLocale::BLOCK_USER_MENU;
$modversion['blocks'][$i]['description'] = SystemLocale::BLOCK_USER_MENU_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_system_user_show';
$modversion['blocks'][$i]['template'] = 'system_block_user.html';
$i++;
$modversion['blocks'][$i]['file'] = 'login.php';
$modversion['blocks'][$i]['name'] = SystemLocale::BLOCK_LOGIN;
$modversion['blocks'][$i]['description'] = SystemLocale::BLOCK_LOGIN_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_system_login_show';
$modversion['blocks'][$i]['template'] = 'system_block_login.html';
$i++;
$modversion['blocks'][$i]['file'] = 'waiting.php';
$modversion['blocks'][$i]['name'] = SystemLocale::BLOCK_WAITING_CONTENTS;
$modversion['blocks'][$i]['description'] = SystemLocale::BLOCK_WAITING_CONTENTS_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_system_waiting_show';
$modversion['blocks'][$i]['template'] = 'system_block_waiting.html';
$i++;
$modversion['blocks'][$i]['file'] = 'main.php';
$modversion['blocks'][$i]['name'] = SystemLocale::BLOCK_MAIN_MENU;
$modversion['blocks'][$i]['description'] = SystemLocale::BLOCK_MAIN_MENU_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_system_main_show';
$modversion['blocks'][$i]['edit_func'] = 'b_system_main_edit';
$modversion['blocks'][$i]['template'] = 'system_block_mainmenu.html';
$i++;
$modversion['blocks'][$i]['file'] = 'info.php';
$modversion['blocks'][$i]['name'] = SystemLocale::BLOCK_SITE_INFORMATION;
$modversion['blocks'][$i]['description'] = SystemLocale::BLOCK_SITE_INFORMATION;
$modversion['blocks'][$i]['show_func'] = 'b_system_info_show';
$modversion['blocks'][$i]['edit_func'] = 'b_system_info_edit';
$modversion['blocks'][$i]['options'] = '320|190|s_poweredby.gif|1';
$modversion['blocks'][$i]['template'] = 'system_block_siteinfo.html';
$i++;
$modversion['blocks'][$i]['file'] = 'online.php';
$modversion['blocks'][$i]['name'] = SystemLocale::BLOCK_WHO_IS_ONLINE;
$modversion['blocks'][$i]['description'] = SystemLocale::BLOCK_WHO_IS_ONLINE_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_system_online_show';
$modversion['blocks'][$i]['template'] = 'system_block_online.html';
$i++;
$modversion['blocks'][$i]['file'] = 'topposters.php';
$modversion['blocks'][$i]['name'] = SystemLocale::BLOCK_TOP_POSTERS;
$modversion['blocks'][$i]['description'] = SystemLocale::BLOCK_TOP_POSTERS_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_system_topposters_show';
$modversion['blocks'][$i]['edit_func'] = 'b_system_topposters_edit';
$modversion['blocks'][$i]['options'] = '10|1';
$modversion['blocks'][$i]['template'] = 'system_block_topusers.html';
$i++;
$modversion['blocks'][$i]['file'] = 'newmembers.php';
$modversion['blocks'][$i]['name'] = SystemLocale::BLOCK_NEW_MEMBERS;
$modversion['blocks'][$i]['description'] = SystemLocale::BLOCK_NEW_MEMBERS_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_system_newmembers_show';
$modversion['blocks'][$i]['options'] = '10|1';
$modversion['blocks'][$i]['edit_func'] = 'b_system_newmembers_edit';
$modversion['blocks'][$i]['template'] = 'system_block_newusers.html';
$i++;
$modversion['blocks'][$i]['file'] = 'themes.php';
$modversion['blocks'][$i]['name'] = SystemLocale::BLOCK_THEMES;
$modversion['blocks'][$i]['description'] = SystemLocale::BLOCK_THEMES_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_system_themes_show';
$modversion['blocks'][$i]['options'] = '0|80';
$modversion['blocks'][$i]['edit_func'] = 'b_system_themes_edit';
$modversion['blocks'][$i]['template'] = 'system_block_themes.html';

// Menu
$modversion['hasMain'] = 0;

// Config categories
$i = 0;
$modversion['configcat']['general']['name'] = SystemLocale::GENERAL_SETTINGS;
$modversion['configcat']['general']['description'] = '';
$i++;
$modversion['configcat']['user']['name'] = XoopsLocale::USER;
$modversion['configcat']['user']['description'] = '';
$i++;
$modversion['configcat']['meta']['name'] = SystemLocale::META_TAGS_AND_FOOTER;
$modversion['configcat']['meta']['description'] = '';
$i++;
$modversion['configcat']['mail']['name'] = XoopsLocale::EMAIL;
$modversion['configcat']['mail']['description'] = '';
$i++;
$modversion['configcat']['censor']['name'] = SystemLocale::WORD_CENSORING;
$modversion['configcat']['censor']['description'] = '';
$i++;
$modversion['configcat']['authentication']['name'] = SystemLocale::AUTHENTICATION;
$modversion['configcat']['authentication']['description'] = '';
$i = 0;
// Site preferences
// Category general
$modversion['config'][$i]['name'] = 'sitename';
$modversion['config'][$i]['title'] = 'CONF_SITE_NAME';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = SystemLocale::CONF_SITE_NAME_DEFAULT;
$i++;
$modversion['config'][$i]['name'] = 'slogan';
$modversion['config'][$i]['title'] = 'CONF_SLOGAN';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = SystemLocale::CONF_SLOGAN_DEFAULT;
$i++;
$modversion['config'][$i]['name'] = 'adminmail';
$modversion['config'][$i]['title'] = 'CONF_ADMIN_EMAIL';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';
$i++;
$modversion['config'][$i]['name'] = 'locale';
$modversion['config'][$i]['title'] = 'CONF_LOCALE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'locale';
$modversion['config'][$i]['valuetype'] = 'other';
$modversion['config'][$i]['default'] = 'en_US';
$i++;
$modversion['config'][$i]['name'] = 'startpage';
$modversion['config'][$i]['title'] = 'CONF_START_PAGE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'startpage';
$modversion['config'][$i]['valuetype'] = 'other';
$modversion['config'][$i]['default'] = '--';
$i++;
$modversion['config'][$i]['name'] = 'server_TZ';
$modversion['config'][$i]['title'] = 'CONF_SERVER_TIMEZONE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'timezone';
$modversion['config'][$i]['valuetype'] = 'float';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'default_TZ';
$modversion['config'][$i]['title'] = 'CONF_DEFAULT_TIMEZONE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'timezone';
$modversion['config'][$i]['valuetype'] = 'float';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'theme_set';
$modversion['config'][$i]['title'] = 'CONF_THEME_SET';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'theme';
$modversion['config'][$i]['valuetype'] = 'other';
$modversion['config'][$i]['default'] = 'default';
$i++;
$modversion['config'][$i]['name'] = 'cpanel';
$modversion['config'][$i]['title'] = 'CONF_CONTROL_PANEL';
$modversion['config'][$i]['description'] = 'CONF_CONTROL_PANEL_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'cpanel';
$modversion['config'][$i]['valuetype'] = 'other';
$modversion['config'][$i]['default'] = 'default';
$i++;
$modversion['config'][$i]['name'] = 'redirect_message_ajax';
$modversion['config'][$i]['title'] = 'CONF_REDIRECT';
$modversion['config'][$i]['description'] = 'CONF_REDIRECT_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'theme_set_allowed';
$modversion['config'][$i]['title'] = 'CONF_THEME_SET_ALLOWED';
$modversion['config'][$i]['description'] = 'CONF_THEME_SET_ALLOWED_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'theme_multi';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('default' => 'default');
$i++;
$modversion['config'][$i]['name'] = 'theme_fromfile';
$modversion['config'][$i]['title'] = 'CONF_THEME_FILE';
$modversion['config'][$i]['description'] = 'CONF_THEME_FILE_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'template_set';
$modversion['config'][$i]['title'] = 'CONF_TEMPLATE_SET';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'tplset';
$modversion['config'][$i]['valuetype'] = 'other';
$modversion['config'][$i]['default'] = 'default';
$i++;
$modversion['config'][$i]['name'] = 'anonymous';
$modversion['config'][$i]['title'] = 'CONF_ANONYMOUS';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = XoopsLocale::ANONYMOUS;
$i++;
$modversion['config'][$i]['name'] = 'gzip_compression';
$modversion['config'][$i]['title'] = 'CONF_GZIP_COMPRESSION';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'usercookie';
$modversion['config'][$i]['title'] = 'CONF_USER_COOKIE';
$modversion['config'][$i]['description'] = 'CONF_USER_COOKIE_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'xoops_user';
$i++;
$modversion['config'][$i]['name'] = 'use_mysession';
$modversion['config'][$i]['title'] = 'CONF_USE_MY_SESSION';
$modversion['config'][$i]['description'] = 'CONF_USE_MY_SESSION_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'session_name';
$modversion['config'][$i]['title'] = 'CONF_SESSION_NAME';
$modversion['config'][$i]['description'] = 'CONF_SESSION_NAME_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'xoops_session';
$i++;
$modversion['config'][$i]['name'] = 'session_expire';
$modversion['config'][$i]['title'] = 'CONF_SESSION_EXPIRE';
$modversion['config'][$i]['description'] = 'CONF_SESSION_EXPIRE_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 15;
$i++;
$modversion['config'][$i]['name'] = 'closesite';
$modversion['config'][$i]['title'] = 'CONF_CLOSE_SITE';
$modversion['config'][$i]['description'] = 'CONF_CLOSE_SITE_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'closesite_okgrp';
$modversion['config'][$i]['title'] = 'CONF_CLOSE_SITE_GROUP';
$modversion['config'][$i]['description'] = 'CONF_CLOSE_SITE_GROUP_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'group_multi';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('1');
$i++;
$modversion['config'][$i]['name'] = 'closesite_text';
$modversion['config'][$i]['title'] = 'CONF_CLOSE_SITE';
$modversion['config'][$i]['description'] = 'CONF_CLOSE_SITE_TEXT_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = SystemLocale::CONF_CLOSE_SITE_DEFAULT;
$i++;
$modversion['config'][$i]['name'] = 'use_ssl';
$modversion['config'][$i]['title'] = 'CONF_USE_SSL';
$modversion['config'][$i]['description'] = 'CONF_USE_SSL_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'sslpost_name';
$modversion['config'][$i]['title'] = 'CONF_SSL_POST_NAME';
$modversion['config'][$i]['description'] = 'CONF_SSL_POST_NAME_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'xoops_ssl';
$i++;
$modversion['config'][$i]['name'] = 'sslloginlink';
$modversion['config'][$i]['title'] = 'CONF_SSL_LINK';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'https://';
$i++;
$modversion['config'][$i]['name'] = 'enable_badips';
$modversion['config'][$i]['title'] = 'CONF_ENABLE_BAD_IPS';
$modversion['config'][$i]['description'] = 'CONF_ENABLE_BAD_IPS_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'bad_ips';
$modversion['config'][$i]['title'] = 'CONF_BAD_IPS';
$modversion['config'][$i]['description'] = 'CONF_BAD_IPS_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('127.0.0.1');
$i++;
$modversion['config'][$i]['name'] = 'module_cache';
$modversion['config'][$i]['title'] = 'CONF_MODULE_CACHE';
$modversion['config'][$i]['description'] = 'CONF_MODULE_CACHE_DESC';
$modversion['config'][$i]['category'] = 'general';
$modversion['config'][$i]['formtype'] = 'module_cache';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = '';
$i++;
// Category user
$modversion['config'][$i]['name'] = 'allow_register';
$modversion['config'][$i]['title'] = 'CONF_ALLOW_REGISTRATION';
$modversion['config'][$i]['description'] = 'CONF_ALLOW_REGISTRATION_DESC';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'minpass';
$modversion['config'][$i]['title'] = 'CONF_MIN_PASS';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 8;
$i++;
$modversion['config'][$i]['name'] = 'minuname';
$modversion['config'][$i]['title'] = 'CONF_MIN_USERNAME';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 3;
$i++;
$modversion['config'][$i]['name'] = 'maxuname';
$modversion['config'][$i]['title'] = 'CONF_MAX_USERNAME';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 10;
$i++;
$modversion['config'][$i]['name'] = 'allow_chgmail';
$modversion['config'][$i]['title'] = 'CONF_ALLOW_CHANGE_EMAIL';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'welcome_type';
$modversion['config'][$i]['title'] = 'CONF_WELCOME_TYPE';
$modversion['config'][$i]['description'] = 'CONF_WELCOME_TYPE_DESC';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['options'] = array(
    'CONF_WELCOME_TYPE_NONE' => 0,
    'CONF_WELCOME_TYPE_EMAIL' => 1,
    'CONF_WELCOME_TYPE_PM' => 2,
    'CONF_WELCOME_TYPE_BOTH'  => 3
);
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'new_user_notify';
$modversion['config'][$i]['title'] = 'CONF_NEW_USER_NOTIFY';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'new_user_notify_group';
$modversion['config'][$i]['title'] = 'CONF_NOTIFY_TO';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'group';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'activation_type';
$modversion['config'][$i]['title'] = 'CONF_ACTIVATION_TYPE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['options'] = array(
    'CONF_USER_ACTIVATION'  => 0,
    'CONF_AUTO_ACTIVATION'  => 1,
    'CONF_ADMIN_ACTIVATION' => 2
);
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'activation_group';
$modversion['config'][$i]['title'] = 'CONF_ACTIVATION_GROUP';
$modversion['config'][$i]['description'] = 'CONF_ACTIVATION_GROUP_DESC';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'group';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'uname_test_level';
$modversion['config'][$i]['title'] = 'CONF_USERNAME_LEVEL';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['options'] = array(
    'CONF_LEVEL_STRICT' => 0,
    'CONF_LEVEL_MEDIUM' => 1,
    'CONF_LEVEL_LIGHT'  => 2
);
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'self_delete';
$modversion['config'][$i]['title'] = 'CONF_SELF_DELETE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'bad_unames';
$modversion['config'][$i]['title'] = 'CONF_BAD_USERNAMES';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('webmaster', '^xoops', '^admin');
$i++;
$modversion['config'][$i]['name'] = 'bad_emails';
$modversion['config'][$i]['title'] = 'CONF_BAD_EMAILS';
$modversion['config'][$i]['description'] = 'CONF_BAD_EMAILS_DESC';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('xoops.org$');
$i++;
$modversion['config'][$i]['name'] = 'reg_dispdsclmr';
$modversion['config'][$i]['title'] = 'CONF_DSPDSCLMR';
$modversion['config'][$i]['description'] = 'CONF_DSPDSCLMR_DESC';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'reg_disclaimer';
$modversion['config'][$i]['title'] = 'CONF_REGDSCLMR';
$modversion['config'][$i]['description'] = 'CONF_DSPDSCLMR_DESC';
$modversion['config'][$i]['category'] = 'user';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'CONF_DISCLAIMER_DEFAULT';
$i++;
// Category meta
$modversion['config'][$i]['name'] = 'meta_keywords';
$modversion['config'][$i]['title'] = 'CONF_METAKEY';
$modversion['config'][$i]['description'] = 'CONF_METAKEY_DESC';
$modversion['config'][$i]['category'] = 'meta';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = SystemLocale::CONF_METAKEY_DEFAULT;
$i++;
$modversion['config'][$i]['name'] = 'meta_description';
$modversion['config'][$i]['title'] = 'CONF_METADESC';
$modversion['config'][$i]['description'] = 'CONF_METADESC_DESC';
$modversion['config'][$i]['category'] = 'meta';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = SystemLocale::CONF_METADESC_DEFAULT;
$i++;
$modversion['config'][$i]['name'] = 'meta_robots';
$modversion['config'][$i]['title'] = 'CONF_METAROBOTS';
$modversion['config'][$i]['description'] = 'CONF_METAROBOTS_DESC';
$modversion['config'][$i]['category'] = 'meta';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['options'] = array(
    'CONF_INDEXFOLLOW'     => 'index,follow',
    'CONF_NOINDEXFOLLOW'   => 'noindex,follow',
    'CONF_INDEXNOFOLLOW'   => 'index,nofollow',
    'CONF_NOINDEXNOFOLLOW' => 'noindex,nofollow'
);
$modversion['config'][$i]['default'] = 'index,follow';
$i++;
$modversion['config'][$i]['name'] = 'meta_rating';
$modversion['config'][$i]['title'] = 'CONF_METARATING';
$modversion['config'][$i]['description'] = 'CONF_METARATING_DESC';
$modversion['config'][$i]['category'] = 'meta';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['options'] = array(
    'CONF_METAOGEN'   => 'general',
    'CONF_METAO14YRS' => '14 years',
    'CONF_METAOREST'  => 'restricted',
    'CONF_METAOMAT'   => 'mature'
);
$modversion['config'][$i]['default'] = 'general';
$i++;
$modversion['config'][$i]['name'] = 'meta_author';
$modversion['config'][$i]['title'] = 'CONF_METAAUTHOR';
$modversion['config'][$i]['description'] = 'CONF_METAAUTHOR_DESC';
$modversion['config'][$i]['category'] = 'meta';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'XOOPS';
$i++;
$modversion['config'][$i]['name'] = 'meta_copyright';
$modversion['config'][$i]['title'] = 'CONF_METACOPYR';
$modversion['config'][$i]['description'] = 'CONF_METACOPYR_DESC';
$modversion['config'][$i]['category'] = 'meta';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = sprintf(SystemLocale::CONF_METACOPYR_DEFAULT, date('Y', time()));
$i++;
$modversion['config'][$i]['name'] = 'footer';
$modversion['config'][$i]['title'] = 'CONF_FOOTER';
$modversion['config'][$i]['description'] = 'CONF_FOOTER_DESC';
$modversion['config'][$i]['category'] = 'meta';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = sprintf(SystemLocale::CONF_FOOTER_DEFAULT, date('Y', time()));
$i++;
// Category mail
$modversion['config'][$i]['name'] = 'from';
$modversion['config'][$i]['title'] = 'CONF_MAILFROM';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'mail';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';
$i++;
$modversion['config'][$i]['name'] = 'fromname';
$modversion['config'][$i]['title'] = 'CONF_MAILFROMNAME';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'mail';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';
$i++;
$modversion['config'][$i]['name'] = 'fromuid';
$modversion['config'][$i]['title'] = 'CONF_MAILFROMUID';
$modversion['config'][$i]['description'] = 'CONF_MAILFROMUID_DESC';
$modversion['config'][$i]['category'] = 'mail';
$modversion['config'][$i]['formtype'] = 'user';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'mailmethod';
$modversion['config'][$i]['title'] = 'CONF_MAILERMETHOD';
$modversion['config'][$i]['description'] = 'CONF_MAILERMETHOD_DESC';
$modversion['config'][$i]['category'] = 'mail';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['options'] = array(
    'PHP mail()' => 'mail',
    'sendmail'   => 'sendmail',
    'SMTP'       => 'smtp',
    'SMTPAuth'   => 'smtpauth'
);
$modversion['config'][$i]['default'] = 'mail';
$i++;
$modversion['config'][$i]['name'] = 'sendmailpath';
$modversion['config'][$i]['title'] = 'CONF_SENDMAILPATH';
$modversion['config'][$i]['description'] = 'CONF_SENDMAILPATH_DESC';
$modversion['config'][$i]['category'] = 'mail';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '/usr/sbin/sendmail';
$i++;
$modversion['config'][$i]['name'] = 'smtphost';
$modversion['config'][$i]['title'] = 'CONF_SMTPHOST';
$modversion['config'][$i]['description'] = 'CONF_SMTPHOST_DESC';
$modversion['config'][$i]['category'] = 'mail';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = 'a:1:{i:0;s:0:\"\";}';
$i++;
$modversion['config'][$i]['name'] = 'smtpuser';
$modversion['config'][$i]['title'] = 'CONF_SMTPUSER';
$modversion['config'][$i]['description'] = 'CONF_SMTPUSER_DESC';
$modversion['config'][$i]['category'] = 'mail';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';
$i++;
$modversion['config'][$i]['name'] = 'smtppass';
$modversion['config'][$i]['title'] = 'CONF_SMTPPASS';
$modversion['config'][$i]['description'] = 'CONF_SMTPPASS_DESC';
$modversion['config'][$i]['category'] = 'mail';
$modversion['config'][$i]['formtype'] = 'password';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';
$i++;
// Category censor
$modversion['config'][$i]['name'] = 'censor_enable';
$modversion['config'][$i]['title'] = 'CONF_DOCENSOR';
$modversion['config'][$i]['description'] = 'CONF_DOCENSOR_DESC';
$modversion['config'][$i]['category'] = 'censor';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'censor_words';
$modversion['config'][$i]['title'] = 'CONF_CENSORWRD';
$modversion['config'][$i]['description'] = 'CONF_CENSORWRD_DESC';
$modversion['config'][$i]['category'] = 'censor';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('fuck', 'shit');
$i++;
$modversion['config'][$i]['name'] = 'censor_replace';
$modversion['config'][$i]['title'] = 'CONF_CENSORRPLC';
$modversion['config'][$i]['description'] = 'CONF_CENSORRPLC_DESC';
$modversion['config'][$i]['category'] = 'censor';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '#OOPS#';
$i++;
// Category authentication
$modversion['config'][$i]['name'] = 'auth_method';
$modversion['config'][$i]['title'] = 'CONF_AUTHMETHOD';
$modversion['config'][$i]['description'] = 'CONF_AUTHMETHOD_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['options'] = array(
    'CONF_AUTH_CONFOPTION_XOOPS' => 'xoops',
    'CONF_AUTH_CONFOPTION_LDAP'  => 'ldap',
    'CONF_AUTH_CONFOPTION_AD'    => 'ads'
);
$modversion['config'][$i]['default'] = 'xoops';
$i++;
$modversion['config'][$i]['name'] = 'ldap_port';
$modversion['config'][$i]['title'] = 'CONF_LDAP_PORT';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 389;
$i++;
$modversion['config'][$i]['name'] = 'ldap_server';
$modversion['config'][$i]['title'] = 'CONF_LDAP_SERVER';
$modversion['config'][$i]['description'] = 'CONF_LDAP_SERVER_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'your directory server';
$i++;
$modversion['config'][$i]['name'] = 'ldap_base_dn';
$modversion['config'][$i]['title'] = 'CONF_LDAP_BASE_DN';
$modversion['config'][$i]['description'] = 'CONF_LDAP_BASE_DN_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'dc=xoops,dc=org';
$i++;
$modversion['config'][$i]['name'] = 'ldap_manager_dn';
$modversion['config'][$i]['title'] = 'CONF_LDAP_MANAGER_DN';
$modversion['config'][$i]['description'] = 'CONF_LDAP_MANAGER_DN_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'manager_dn';
$i++;
$modversion['config'][$i]['name'] = 'ldap_manager_pass';
$modversion['config'][$i]['title'] = 'CONF_LDAP_MANAGER_PASS';
$modversion['config'][$i]['description'] = 'CONF_LDAP_MANAGER_PASS_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'password';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'manager_pass';
$i++;
$modversion['config'][$i]['name'] = 'ldap_version';
$modversion['config'][$i]['title'] = 'CONF_LDAP_VERSION';
$modversion['config'][$i]['description'] = 'CONF_LDAP_VERSION_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '3';
$i++;
$modversion['config'][$i]['name'] = 'ldap_users_bypass';
$modversion['config'][$i]['title'] = 'CONF_LDAP_USERS_BYPASS';
$modversion['config'][$i]['description'] = 'CONF_LDAP_USERS_BYPASS_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('admin');
$i++;
$modversion['config'][$i]['name'] = 'ldap_loginname_asdn';
$modversion['config'][$i]['title'] = 'CONF_LDAP_LOGINNAME_ASDN';
$modversion['config'][$i]['description'] = 'CONF_LDAP_LOGINNAME_ASDN_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'ldap_loginldap_attr';
$modversion['config'][$i]['title'] = 'CONF_LDAP_LOGINLDAP_ATTR';
$modversion['config'][$i]['description'] = 'CONF_LDAP_LOGINLDAP_ATTR_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'uid';
$i++;
$modversion['config'][$i]['name'] = 'ldap_filter_person';
$modversion['config'][$i]['title'] = 'CONF_LDAP_FILTER_PERSON';
$modversion['config'][$i]['description'] = 'CONF_LDAP_FILTER_PERSON_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';
$i++;
$modversion['config'][$i]['name'] = 'ldap_domain_name';
$modversion['config'][$i]['title'] = 'CONF_LDAP_DOMAIN_NAME';
$modversion['config'][$i]['description'] = 'CONF_LDAP_DOMAIN_NAME_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'mydomain';
$i++;
$modversion['config'][$i]['name'] = 'ldap_provisionning';
$modversion['config'][$i]['title'] = 'CONF_LDAP_PROVIS';
$modversion['config'][$i]['description'] = 'CONF_LDAP_PROVIS_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'ldap_provisionning_group';
$modversion['config'][$i]['title'] = 'CONF_LDAP_PROVIS_GROUP';
$modversion['config'][$i]['description'] = 'CONF_LDAP_PROVIS_GROUP_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'group_multi';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = 'a:1:{i:0;s:1:\"2\";}';
$i++;
$modversion['config'][$i]['name'] = 'ldap_mail_attr';
$modversion['config'][$i]['title'] = 'CONF_LDAP_MAIL_ATTR';
$modversion['config'][$i]['description'] = 'CONF_LDAP_MAIL_ATTR_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'mail';
$i++;
$modversion['config'][$i]['name'] = 'ldap_givenname_attr';
$modversion['config'][$i]['title'] = 'CONF_LDAP_GIVENNAME_ATTR';
$modversion['config'][$i]['description'] = 'CONF_LDAP_GIVENNAME_ATTR_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'givenname';
$i++;
$modversion['config'][$i]['name'] = 'ldap_surname_attr';
$modversion['config'][$i]['title'] = 'CONF_LDAP_SURNAME_ATTR';
$modversion['config'][$i]['description'] = 'CONF_LDAP_SURNAME_ATTR_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'sn';
$i++;
$modversion['config'][$i]['name'] = 'ldap_field_mapping';
$modversion['config'][$i]['title'] = 'CONF_LDAP_FIELD_MAPPING_ATTR';
$modversion['config'][$i]['description'] = 'CONF_LDAP_FIELD_MAPPING_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'email=mail|name=displayname';
$i++;
$modversion['config'][$i]['name'] = 'ldap_provisionning_upd';
$modversion['config'][$i]['title'] = 'CONF_LDAP_PROVIS_UPD';
$modversion['config'][$i]['description'] = 'CONF_LDAP_PROVIS_UPD_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'ldap_use_TLS';
$modversion['config'][$i]['title'] = 'CONF_LDAP_USETLS';
$modversion['config'][$i]['description'] = 'CONF_LDAP_USETLS_DESC';
$modversion['config'][$i]['category'] = 'authentication';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;

$i++;
$modversion['config'][$i]['name'] = 'usetips';
$modversion['config'][$i]['title'] = 'CONF_HELP_ONLINE';
$modversion['config'][$i]['description'] = 'CONF_HELP_ONLINE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;

$icons = XoopsLists::getDirListAsArray(XOOPS_ROOT_PATH . '/modules/system/images/icons');
$modversion['config'][$i]['name'] = 'typeicons';
$modversion['config'][$i]['title'] = 'CONF_ICONS';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'default';
$modversion['config'][$i]['options'] = $icons;
$i++;
$breadcrumb = XoopsLists::getDirListAsArray(XOOPS_ROOT_PATH . '/modules/system/images/breadcrumb');
$modversion['config'][$i]['name'] = 'typebreadcrumb';
$modversion['config'][$i]['title'] = 'CONF_BREADCRUMB';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'default';
$modversion['config'][$i]['options'] = $breadcrumb;
$i++;
$jquery_theme = XoopsLists::getDirListAsArray(XOOPS_ROOT_PATH . '/media/jquery/ui');
$modversion['config'][$i]['name'] = 'jquery_theme';
$modversion['config'][$i]['title'] = 'CONF_JQUERY_THEME';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'base';
$modversion['config'][$i]['options'] = $jquery_theme;

$i++;
$modversion['config'][$i]['name'] = 'active_blocksadmin';
$modversion['config'][$i]['title'] = '';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'hidden';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'active_filemanager';
$modversion['config'][$i]['title'] = '';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'hidden';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'active_groups';
$modversion['config'][$i]['title'] = '';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'hidden';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'active_modulesadmin';
$modversion['config'][$i]['title'] = '';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'hidden';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'active_preferences';
$modversion['config'][$i]['title'] = '';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'hidden';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'active_tplsets';
$modversion['config'][$i]['title'] = '';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'hidden';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'active_users';
$modversion['config'][$i]['title'] = '';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'hidden';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] = 'groups_pager';
$modversion['config'][$i]['title'] = 'CONF_GROUPS_PER_PAGE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 15;
$i++;
$modversion['config'][$i]['name'] = 'users_pager';
$modversion['config'][$i]['title'] = 'CONF_USERS_PER_PAGE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 20;

$i++;
$editors = XoopsLists::getDirListAsArray(XOOPS_ROOT_PATH . '/class/xoopseditor');
$modversion['config'][$i]['name'] = 'blocks_editor';
$modversion['config'][$i]['title'] = 'CONF_BLOCKS_EDITOR';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'dhtmltextarea';
$modversion['config'][$i]['options'] = $editors;
$i++;
$modversion['config'][$i]['name'] = 'general_editor';
$modversion['config'][$i]['title'] = 'CONF_GENERAL_EDITOR';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'dhtmltextarea';
$modversion['config'][$i]['options'] = $editors;
$i++;
$modversion['config'][$i]['name'] = 'redirect';
$modversion['config'][$i]['title'] = '';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'hidden';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'admin.php?fct=preferences';