<?php
require_once(dirname(__FILE__).'/../../../init_new.php');

use Xoops\Core\FixedGroups;

/*
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-19 at 21:46:46.
 */
 
/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class FixedGroupsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FixedGroups
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // $this->object = new FixedGroups();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testConstants()
    {
        $this->assertTrue(is_numeric(FixedGroups::ADMIN));
        $this->assertTrue(is_numeric(FixedGroups::USERS));
        $this->assertTrue(is_numeric(FixedGroups::ANONYMOUS));
        $this->assertTrue(is_numeric(FixedGroups::REMOVED));
    }
}
