<?php
namespace Xmf\Database;

require_once(dirname(__FILE__).'/../../../init_new.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-05 at 08:07:15.
 */

/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class TableLoadTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TableLoad
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TableLoad;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xmf\Database\TableLoad::loadTableFromArray
     * @todo   Implement testLoadTableFromArray().
     */
    public function testLoadTableFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\TableLoad::loadTableFromYamlFile
     * @todo   Implement testLoadTableFromYamlFile().
     */
    public function testLoadTableFromYamlFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\TableLoad::truncateTable
     */
    public function testTruncateTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\TableLoad::countRows
     */
    public function testRowCount()
    {
        $actual = $this->object->countRows('system_user');
        $this->assertTrue(is_integer($actual));
        $this->assertTrue($actual >= 1);
    }
}
