<?php
namespace Xmf\Database;

require_once(dirname(__FILE__).'/../../../init_new.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-22 at 19:56:36.
 */
 
/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class TablesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Tables
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tables;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xmf\Database\Tables::name
     * @todo   Implement testName().
     */
    public function testName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::addColumn
     * @todo   Implement testAddColumn().
     */
    public function testAddColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::addPrimaryKey
     * @todo   Implement testAddPrimaryKey().
     */
    public function testAddPrimaryKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::addTable
     * @todo   Implement testAddTable().
     */
    public function testAddTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::useTable
     * @todo   Implement testUseTable().
     */
    public function testUseTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::alterColumn
     * @todo   Implement testAlterColumn().
     */
    public function testAlterColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::copyTable
     * @todo   Implement testCopyTable().
     */
    public function testCopyTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::createIndex
     * @todo   Implement testCreateIndex().
     */
    public function testCreateIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::dropColumn
     * @todo   Implement testDropColumn().
     */
    public function testDropColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::dropIndex
     * @todo   Implement testDropIndex().
     */
    public function testDropIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::dropIndexes
     * @todo   Implement testDropIndexes().
     */
    public function testDropIndexes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::dropPrimaryKey
     * @todo   Implement testDropPrimaryKey().
     */
    public function testDropPrimaryKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::dropTable
     * @todo   Implement testDropTable().
     */
    public function testDropTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::renameTable
     * @todo   Implement testRenameTable().
     */
    public function testRenameTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::setTableOptions
     * @todo   Implement testSetTableOptions().
     */
    public function testSetTableOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::queueReset
     * @todo   Implement testQueueReset().
     */
    public function testQueueReset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::queueExecute
     * @todo   Implement testQueueExecute().
     */
    public function testQueueExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::insert
     * @todo   Implement testInsert().
     */
    public function testInsert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::truncate
     * @todo   Implement testTruncate().
     */
    public function testTruncate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::renderTableCreate
     * @todo   Implement testRenderTableCreate().
     */
    public function testRenderTableCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::getLastError
     * @todo   Implement testGetLastError().
     */
    public function testGetLastError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::getLastErrNo
     * @todo   Implement testGetLastErrNo().
     */
    public function testGetLastErrNo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::dumpTables
     * @todo   Implement testDumpTables().
     */
    public function testDumpTables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Database\Tables::dumpQueue
     * @todo   Implement testDumpQueue().
     */
    public function testDumpQueue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
