<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*/

/**
 * avatars extension
 *
 * @copyright       XOOPS Project (http://xoops.org)
 * @license         GNU GPL 2 or later (http://www.gnu.org/licenses/gpl-2.0.html)
 * @package         avatar
 * @since           2.6.0
 * @author          Mage Grégory (AKA Mage)
 * @version         $Id$
 */
$modversion = [];
$modversion['name'] = _MI_PHPMAILER_NAME;
$modversion['description'] = _MI_PHPMAILER_DESC;
$modversion['version'] = 0.1;
$modversion['author'] = 'Richard Griffith';
$modversion['nickname'] = 'geekwright';
$modversion['credits'] = 'The XOOPS Project';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = 'http://www.gnu.org/licenses/gpl-2.0.html';
$modversion['official'] = 1;
$modversion['help'] = 'page=help';
$modversion['image'] = 'icons/logo.png';
$modversion['dirname'] = 'phpmailer';
//about
$modversion['release_date'] = '2018/03/26';
$modversion['module_website_url'] = 'https://www.xoops.org/';
$modversion['module_website_name'] = 'XOOPS';
$modversion['module_status'] = 'ALPHA';
$modversion['min_php'] = '7.1.0';
$modversion['min_xoops'] = '2.6.0';

// paypal
$modversion['paypal'] = [
    'business' => 'xoopsfoundation@gmail.com',
    'item_name' => 'Donation : ' . _MI_PHPMAILER_NAME,
    'amount' => 0,
    'currency_code' => 'USD',
];

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin'] = true;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

/*
 Manage extension
 */
$modversion['extension'] = 1;
$modversion['extension_module'][] = 'system';

// Preferences
// Category mail

$modversion['config'][] = [
    'name' => 'mailmethod',
    'title' => '_MI_PHPMAILER_CONF_MAILERMETHOD',
    'description' => '_MI_PHPMAILER_CONF_MAILERMETHOD_DESC',
    'formtype' => 'select',
    'valuetype' => 'text',
    'options' => [
        'PHP mail()' => 'mail',
        'sendmail' => 'sendmail',
        'SMTP' => 'smtp',
        'SMTPAuth' => 'smtpauth',
    ],
    'default' => 'mail',
];

$modversion['config'][] = [
    'name' => 'smtp_host',
    'title' => '_MI_PHPMAILER_CONF_SMTPHOST',
    'description' => '_MI_PHPMAILER_CONF_SMTPHOST_DESC',
    'formtype' => 'textbox',
    'valuetype' => 'text',
    'default' => '',
];

$modversion['config'][] = [
    'name' => 'smtp_usetls',
    'title' => '_MI_PHPMAILER_CONF_SMTP_USE_TLS',
    'description' => '_MI_PHPMAILER_CONF_SMTP_USE_TLS_DESC',
    'formtype' => 'yesno',
    'valuetype' => 'int',
    'default' => '1',
];

$modversion['config'][] = [
    'name' => 'smtp_user',
    'title' => '_MI_PHPMAILER_CONF_SMTPUSER',
    'description' => '_MI_PHPMAILER_CONF_SMTPUSER_DESC',
    'formtype' => 'textbox',
    'valuetype' => 'text',
    'default' => '',
];

$modversion['config'][] = [
    'name' => 'smtp_pass',
    'title' => '_MI_PHPMAILER_CONF_SMTPPASS',
    'description' => '_MI_PHPMAILER_CONF_SMTPPASS_DESC',
    'formtype' => 'password',
    'valuetype' => 'text',
    'default' => '',
];

$modversion['config'][] = [
    'name' => 'smtp_debug',
    'title' => '_MI_PHPMAILER_CONF_SMTPDEBUG',
    'description' => '_MI_PHPMAILER_CONF_SMTPDEBUG_DESC',
    'formtype' => 'select',
    'valuetype' => 'int',
    'options' => [
        'Off' => 0,
        'Commands' => 1,
        'Data and commands' => 2,
        'Data, commands and connection status' => 3,
        'Low-level data output' => 4,
    ],
    'default' => 'mail',
];

$modversion['config'][] = [
    'name' => 'sendmailpath',
    'title' => '_MI_PHPMAILER_CONF_SENDMAILPATH',
    'description' => '_MI_PHPMAILER_CONF_SENDMAILPATH_DESC',
    'formtype' => 'textbox',
    'valuetype' => 'text',
    'default' => '/usr/sbin/sendmail',
];
