<?php
namespace Xoops\Form;

require_once(dirname(__FILE__).'/../../../init_mini.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-18 at 21:59:23.
 */
 
/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class ButtonTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Button
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Button('button_caption', 'button_name', 'button_value');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xoops\Form\Button::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        $x = $this->object->getType();
        $this->assertSame('button',$x);
    }

    /**
     * @covers Xoops\Form\Button::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        $x = $this->object->render();
        $name = 'button_name';
        $caption = 'button_caption';
        $value = 'button_value';
        $this->assertTrue(false !== strpos($x, '<input type="button"'));
        $this->assertTrue(false !== strpos($x, 'name="' . $name .'"'));
        $this->assertTrue(false !== strpos($x, 'id="' . $name .'"'));
        $this->assertTrue(false !== strpos($x, 'title="' . $caption .'"'));
        $this->assertTrue(false !== strpos($x, 'value="' . $value .'"'));
    }
}
