<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*/

/**
 * Extended User Profile
 *
 * @copyright       2000-2016 XOOPS Project (http://xoops.org)
 * @license         GNU GPL 2 or later (http://www.gnu.org/licenses/gpl-2.0.html)
 * @package         profile
 * @since           2.3.0
 * @author          Jan Pedersen
 * @author          Taiwen Jiang <phppp@users.sourceforge.net>
 */
$xoops = Xoops::getInstance();

$modversion = [];
$modversion['name'] = _PROFILE_MI_NAME;
$modversion['version'] = 1.62;
$modversion['description'] = _PROFILE_MI_DESC;
$modversion['author'] = 'Jan Pedersen; Taiwen Jiang (phppp@users.sourceforge.net); alfred (myxoops@t-online.de); Wishcraft (simon@xoops.org)';
$modversion['credits'] = 'Ackbarr, mboyden, marco, mamba,trabis, etc.';
$modversion['help'] = 'page=help';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = 'http://www.gnu.org/licenses/gpl-2.0.html';
$modversion['image'] = 'images/logo.png';
$modversion['dirname'] = 'profile';

//about
$modversion['release_date'] = '2011/10/08';
$modversion['module_website_url'] = 'http://www.xoops.org/';
$modversion['module_website_name'] = 'XOOPS';
$modversion['module_status'] = 'RC';
$modversion['min_php'] = '5.3.7';
$modversion['min_xoops'] = '2.6.0';

// paypal
$modversion['paypal'] = [
    'business' => 'xoopsfoundation@gmail.com',
    'item_name' => 'Donation : ' . _PROFILE_MI_DESC,
    'amount' => 0,
    'currency_code' => 'USD',
];

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Scripts to run upon installation or update
$modversion['onInstall'] = 'include/install.php';
$modversion['onUpdate'] = 'include/update.php';

// Menu
$modversion['hasMain'] = 1;

// Table definitions
$modversion['schema'] = 'sql/schema.yml';
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables (without prefix!)
$modversion['tables'] = [
    'profile_category',
    'profile_profile',
    'profile_field',
    'profile_visibility',
    'profile_regstep',
];

// Config items
$modversion['config'][] = [
    'name' => 'profile_search',
    'title' => '_PROFILE_MI_PROFILE_SEARCH',
    'description' => '',
    'formtype' => 'yesno',
    'valuetype' => 'int',
];
