<?php
namespace Xoops\Form;

require_once(dirname(__FILE__).'/../../../init_new.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-18 at 21:59:23.
 */
 
/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class ButtonTrayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ButtonTray
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ButtonTray('name');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xoops\Form\ButtonTray::getType
     */
    public function testGetType()
    {
        $value = $this->object->getType();
        $this->assertSame('submit',$value);
    }

    /**
     * @covers Xoops\Form\ButtonTray::render
     */
    public function testRender()
    {
        $value = $this->object->render();
        $this->assertTrue(is_string($value));
        $this->assertTrue(false !== strpos($value, '<input type="button"'));
        
        $object = new ButtonTray('name2','','','',true);
        $value = $object->render();
        $this->assertTrue(is_string($value));
        $this->assertTrue(false !== strpos($value, '<input type="submit"'));
        $this->assertTrue(false !== strpos($value, '<input type="button"'));
    }
}
