<?php
namespace Xoops\Form;

require_once(dirname(__FILE__).'/../../../init_new.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-18 at 21:59:23.
 */

/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class ContainerInterfaceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Button
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if (method_exists($this, 'createMock')) {
            $this->object = $this->createMock('\Xoops\Form\ContainerInterface');
        } else { // need phpunit 4.8 for PHP 5.5
            $this->object = $this->getMock('\Xoops\Form\ContainerInterface');
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xoops\Form\ContainerInterface::addElement
     * @covers Xoops\Form\ContainerInterface::getRequired
     * @covers Xoops\Form\ContainerInterface::getElements
     */
    public function testRender()
    {
        $element = new Raw('For Testing');
        $this->assertNull($this->object->addElement(new Raw('For Testing')));
        $this->assertNull($this->object->getRequired());
        $this->assertNull($this->object->getElements(false));
    }
}
