<?php
namespace Xoops\Form;

require_once(dirname(__FILE__).'/../../../init_new.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-18 at 21:59:24.
 */
 
/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class ElementTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Element
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('Xoops\Form\Element');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xoops\Form\Element::setAttribute
     * @todo   Implement testSetAttribute().
     */
    public function testSetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xoops\Form\Element::getAttribute
     * @todo   Implement testGetAttribute().
     */
    public function testGetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xoops\Form\Element::hasAttribute
     * @todo   Implement testHasAttribute().
     */
    public function testHasAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xoops\Form\Element::addAttribute
     * @todo   Implement testAddAttribute().
     */
    public function testAddAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xoops\Form\Element::renderAttributeString
     */
    public function testRenderAttributeString()
    {
        $value = $this->object->renderAttributeString();
        $this->assertTrue(is_string($value));
    }

    /**
     * @covers Xoops\Form\Element::getValue
     */
    public function testGetValue()
    {
        $name = 'name';
        $this->object->setValue($name);
        $value = $this->object->getValue();
        $this->assertSame($name, $value);
        
        $names = array('name1', 'name2');
        $this->object->setValue($names);
        $value = $this->object->getValue();
        $tmp = $names;
        array_unshift($tmp, $name);
        $this->assertSame($tmp, $value);
    }

    /**
     * @covers Xoops\Form\Element::setValue
     */
    public function testSetValue()
    {
        // see testGetValue
    }

    /**
     * @covers Xoops\Form\Element::setName
     */
    public function testSetName()
    {
        // see testGetName
    }

    /**
     * @covers Xoops\Form\Element::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        $name = 'name';
        $this->object->setName($name);
        $value = $this->object->getName();
        $this->assertSame($name, $value);
    }

    /**
     * @covers Xoops\Form\Element::setAccessKey
     * @todo   Implement testSetAccessKey().
     */
    public function testSetAccessKey()
    {
        // see testGetAccessKey
    }

    /**
     * @covers Xoops\Form\Element::getAccessKey
     * @todo   Implement testGetAccessKey().
     */
    public function testGetAccessKey()
    {
        $key = 'name';
        $this->object->setAccessKey($key);
        $value = $this->object->getAccessKey();
        $this->assertSame($key, $value);
    }

    /**
     * @covers Xoops\Form\Element::getAccessString
     * @todo   Implement testGetAccessString().
     */
    public function testGetAccessString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xoops\Form\Element::setClass
     * @todo   Implement testSetClass().
     */
    public function testSetClass()
    {
        // set testGetClass
    }

    /**
     * @covers Xoops\Form\Element::getClass
     */
    public function testGetClass()
    {
        $name = 'name';
        $this->object->setClass($name);
        $value = $this->object->getClass();
        $this->assertSame($name, $value);
    }

    /**
     * @covers Xoops\Form\Element::setPattern
     */
    public function testSetPattern()
    {
        // see testGetPattern
    }

    /**
     * @covers Xoops\Form\Element::getPattern
     */
    public function testGetPattern()
    {
        $name = 'name';
        $this->object->setPattern($name);
        $value = $this->object->getPattern();
        $this->assertSame($name, $value);
    }

    /**
     * @covers Xoops\Form\Element::getPatternDescription
     * @todo   Implement testGetPatternDescription().
     */
    public function testGetPatternDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xoops\Form\Element::setDatalist
     * @todo   Implement testSetDatalist().
     */
    public function testSetDatalist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xoops\Form\Element::getDatalist
     * @todo   Implement testGetDatalist().
     */
    public function testGetDatalist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xoops\Form\Element::isDatalist
     * @todo   Implement testIsDatalist().
     */
    public function testIsDatalist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xoops\Form\Element::setCaption
     */
    public function testSetCaption()
    {
        // see testGetCaption
    }

    /**
     * @covers Xoops\Form\Element::getCaption
     */
    public function testGetCaption()
    {
        $name = 'name';
        $this->object->setCaption($name);
        $value = $this->object->getCaption();
        $this->assertSame($name, $value);
    }

    /**
     * @covers Xoops\Form\Element::setTitle
     */
    public function testSetTitle()
    {
        // see testGetTitle
    }

    /**
     * @covers Xoops\Form\Element::getTitle
     */
    public function testGetTitle()
    {
        $name = 'name';
        $this->object->setTitle($name);
        $value = $this->object->getTitle();
        $this->assertSame($name, $value);
    }

    /**
     * @covers Xoops\Form\Element::setDescription
     */
    public function testSetDescription()
    {
        // see testGetDescription
    }

    /**
     * @covers Xoops\Form\Element::getDescription
     */
    public function testGetDescription()
    {
        $name = 'name';
        $this->object->setDescription($name);
        $value = $this->object->getDescription();
        $this->assertSame($name, $value);
    }

    /**
     * @covers Xoops\Form\Element::setHidden
     */
    public function testSetHidden()
    {
        // see testIsHidden
    }

    /**
     * @covers Xoops\Form\Element::isHidden
     */
    public function testIsHidden()
    {
        $value = $this->object->isHidden();
        $this->assertFalse($value);
        $this->object->setHidden();
        $value = $this->object->isHidden();
        $this->assertTrue($value);
    }

    /**
     * @covers Xoops\Form\Element::setRequired
     */
    public function testSetRequired()
    {
        // see testIsRequired
    }

    /**
     * @covers Xoops\Form\Element::isRequired
     */
    public function testIsRequired()
    {
        $value = $this->object->isRequired();
        $this->assertFalse($value);
        $this->object->setRequired();
        $value = $this->object->isRequired();
        $this->assertTrue($value);
    }

    /**
     * @covers Xoops\Form\Element::setExtra
     */
    public function testSetExtra()
    {
        // see testGetExtra
    }

    /**
     * @covers Xoops\Form\Element::getExtra
     */
    public function testGetExtra()
    {
        $name = 'name';
        $this->object->setExtra($name);
        $value = $this->object->getExtra();
        $this->assertSame($name, $value);
    }

    /**
     * @covers Xoops\Form\Element::renderValidationJS
     */
    public function testRenderValidationJS()
    {
        $value = $this->object->renderValidationJS();
        $this->assertFalse($value);
    }

    /**
     * @covers Xoops\Form\Element::getMaxcols
     */
    public function testGetMaxcols()
    {
        $value = $this->object->getMaxcols();
        $this->assertTrue(is_int($value));
    }
}
