<?php
namespace Xoops\Core\Handler;

require_once __DIR__ . '/../../../../init_new.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-22 at 18:04:42.
 */
class FactorySpecTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FactorySpec
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $factory = Factory::getInstance();
        $this->object = FactorySpec::getInstance($factory);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xoops\Core\Handler\FactorySpec::getInstance
     */
    public function testGetInstance()
    {
        $factory = Factory::getInstance();
        $instance = FactorySpec::getInstance($factory);
        $this->assertInstanceOf('\Xoops\Core\Handler\FactorySpec', $instance);
        $this->assertNotSame($this->object, $instance);
    }

    /**
     * @covers Xoops\Core\Handler\FactorySpec::scheme
     * @covers Xoops\Core\Handler\FactorySpec::getScheme
     */
    public function testScheme()
    {
        $instance = $this->object->scheme('testing');
        $this->assertInstanceOf('\Xoops\Core\Handler\FactorySpec', $instance);
        $this->assertEquals('testing', $this->object->getScheme());
    }

    /**
     * @covers Xoops\Core\Handler\FactorySpec::name
     * @covers Xoops\Core\Handler\FactorySpec::getName
     */
    public function testName()
    {
        $instance = $this->object->name('testing');
        $this->assertInstanceOf('\Xoops\Core\Handler\FactorySpec', $instance);
        $this->assertEquals('testing', $this->object->getName());
    }

    /**
     * @covers Xoops\Core\Handler\FactorySpec::dirname
     * @covers Xoops\Core\Handler\FactorySpec::getDirname
     */
    public function testDirname()
    {
        $instance = $this->object->dirname('testing');
        $this->assertInstanceOf('\Xoops\Core\Handler\FactorySpec', $instance);
        $this->assertEquals('testing', $this->object->getDirname());
    }

    /**
     * @covers Xoops\Core\Handler\FactorySpec::optional
     * @covers Xoops\Core\Handler\FactorySpec::getOptional
     */
    public function testOptional()
    {
        $instance = $this->object->optional(true);
        $this->assertInstanceOf('\Xoops\Core\Handler\FactorySpec', $instance);
        $this->assertEquals(true, $this->object->getOptional());
    }

    /**
     * @covers Xoops\Core\Handler\FactorySpec::fqn
     * @covers Xoops\Core\Handler\FactorySpec::getFQN
     */
    public function testFqn()
    {
        $instance = $this->object->fqn('testing');
        $this->assertInstanceOf('\Xoops\Core\Handler\FactorySpec', $instance);
        $this->assertEquals('testing', $this->object->getFQN());
    }

    /**
     * @covers Xoops\Core\Handler\FactorySpec::build
     */
    public function testBuild()
    {
        $name = '\Xoops\Core\Kernel\Handlers\XoopsUserHandler';
        $this->object->scheme('fqn')->name($name);
        $this->assertInstanceOf($name, $this->object->build($this->object));
    }

    /**
     * @expectedException \Xoops\Core\Exception\NoHandlerException
     * @covers Xoops\Core\Handler\FactorySpec::build
     */
    public function testBuild_exception()
    {
        $name = '\Xoops\Core\Kernel\Handlers\NoSuchName';
        $this->object->scheme('fqn')->name($name);
        $this->object->build($this->object);
    }

    /**
     * @covers Xoops\Core\Handler\FactorySpec::build
     */
    public function testBuild_optional()
    {
        $name = '\Xoops\Core\Kernel\Handlers\NoSuchName';
        $this->object->scheme('fqn')->name($name)->optional(true);
        $handler = $this->object->build($this->object);
        $this->assertNull($handler);

        $name = '\Xoops\Core\Kernel\Handlers\XoopsUserHandler';
        $this->object->scheme('fqn')->name($name)->optional(true);
        $handler = $this->object->build($this->object);
        $this->assertInstanceOf('\Xoops\Core\Kernel\Handlers\XoopsUserHandler', $handler);
    }


    /**
     * @covers Xoops\Core\Handler\FactorySpec::getFactory
     */
    public function testGetFactory()
    {
        $factory = Factory::getInstance();
        $this->assertSame($factory, $this->object->getFactory());
    }
}
