<?php
require_once(dirname(__FILE__).'/../../init_new.php');

require_once(XOOPS_TU_ROOT_PATH . '/class/file/folder.php');

/*
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-04 at 10:44:18.
 */
 
/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class XoopsFolderHandlerTest extends \PHPUnit_Framework_TestCase
{
    protected $myClass = 'XoopsFolderHandler';
	
    /**
     * @var XoopsFolderHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new XoopsFolderHandler();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
		
    public function test___construct()
	{
		$instance = new $this->myClass();
		$this->assertInstanceOf($this->myClass, $instance);
    }
	
    public function test___publicProperties()
	{
		$items = array('path', 'sort', 'mode');
		foreach($items as $item) {
			$prop = new ReflectionProperty($this->myClass,$item);
			$this->assertTrue($prop->isPublic());
		}
    }

    /**
     * @covers XoopsFolderHandler::pwd
     * @todo   Implement testPwd().
     */
    public function testPwd()
    {
		$dir = dirname(__FILE__);
		$instance = new $this->myClass($dir, false, false);
		$this->assertTrue(file_exists($dir));
		$pwd = $instance->pwd();
		$this->assertSame($dir,$pwd);
		
		$dir = \XoopsBaseConfig::get('var-path') . '/caches/xoops_cache';
		$instance = new $this->myClass('', false, false);
		$pwd = $instance->pwd();
		$this->assertSame($dir,$pwd);
    }

    /**
     * @covers XoopsFolderHandler::cd
     * @todo   Implement testCd().
     */
    public function testCd()
    {
		$dir = dirname(__FILE__);
		$instance = new $this->myClass($dir, false, false);
		$this->assertTrue(file_exists($dir));
		$cd = $instance->cd($dir);
		$this->assertSame($dir,$cd);
		
		$dir = dirname(__FILE__).'NOT_EXISTING_FOLDER_TEST';
		$instance = new $this->myClass($dir, false, false);
		$this->assertFalse(file_exists($dir));
		$cd = $instance->cd($dir);
		$this->assertFalse($cd);
    }

    /**
     * @covers XoopsFolderHandler::read
     * @todo   Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::find
     * @todo   Implement testFind().
     */
    public function testFind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::findRecursive
     * @todo   Implement testFindRecursive().
     */
    public function testFindRecursive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::isWindowsPath
     * @todo   Implement testIsWindowsPath().
     */
    public function testIsWindowsPath()
    {
		$class = $this->myClass;
		$result = $class::isWindowsPath(dirname(__FILE__));
		$this->assertTrue($result);
		$result = $class::isWindowsPath('unixRelativePath/test/test');
		$this->assertFalse($result);
		$result = $class::isWindowsPath('/unixAbsolutePath/test/test');
		$this->assertFalse($result);
    }

    /**
     * @covers XoopsFolderHandler::isAbsolute
     * @todo   Implement testIsAbsolute().
     */
    public function testIsAbsolute()
    {
		$class = $this->myClass;
		$dir = dirname(__FILE__);
		$result = $class::isAbsolute($dir);
		$this->assertTrue($result);
		$result = $class::isAbsolute('/unixAbsolutePath/test/test');
		$this->assertTrue($result);
		$result = $class::isAbsolute('relativePath/test/test');
		$this->assertFalse($result);
		$result = $class::isAbsolute('relativePath\test\test');
		$this->assertFalse($result);
    }

    /**
     * @covers XoopsFolderHandler::normalizePath
     * @todo   Implement testNormalizePath().
     */
    public function testNormalizePath()
    {
		$class = $this->myClass;
		$dir = dirname(__FILE__);
		$result = $class::isWindowsPath($dir);
		$this->assertTrue($result);
		$result = $class::normalizePath($dir);
		$this->assertSame('\\', $result);
		
		$dir = 'unixRelativePath/test/test';
		$result = $class::isWindowsPath($dir);
		$this->assertFalse($result);
		$result = $class::normalizePath($dir);
		$this->assertSame('/', $result);
    }

    /**
     * @covers XoopsFolderHandler::correctSlashFor
     * @todo   Implement testCorrectSlashFor().
     */
    public function testCorrectSlashFor()
    {
		$class = $this->myClass;
		$dir = dirname(__FILE__);
		$result = $class::isWindowsPath($dir);
		$this->assertTrue($result);
		$result = $class::correctSlashFor($dir);
		$this->assertSame('\\', $result);
		
		$dir = 'unixRelativePath/test/test';
		$result = $class::isWindowsPath($dir);
		$this->assertFalse($result);
		$result = $class::correctSlashFor($dir);
		$this->assertSame('/', $result);
    }

    /**
     * @covers XoopsFolderHandler::slashTerm
     * @todo   Implement testSlashTerm().
     */
    public function testSlashTerm()
    {
		$class = $this->myClass;
		$dir = dirname(__FILE__);
		$result = $class::slashTerm($dir);
		$this->assertSame($dir.'\\', $result);
		
		$dir = dirname(__FILE__).'\\';
		$result = $class::slashTerm($dir);
		$this->assertSame($dir, $result);
		
		$dir = 'unixRelativePath/test/test';
		$result = $class::slashTerm($dir);
		$this->assertSame($dir.'/', $result);
		
		$dir = 'unixRelativePath/test/test/';
		$result = $class::slashTerm($dir);
		$this->assertSame($dir, $result);
    }

    /**
     * @covers XoopsFolderHandler::addPathElement
     * @todo   Implement testAddPathElement().
     */
    public function testAddPathElement()
    {
		$class = $this->myClass;
		$element = 'element';
		$dir = dirname(__FILE__);
		$result = $class::addPathElement($dir,$element);
		$this->assertSame($dir.'\\'.$element, $result);
		
		$dir = dirname(__FILE__).'\\';
		$result = $class::addPathElement($dir,$element);
		$this->assertSame($dir.$element, $result);
		
		$dir = 'unixRelativePath/test/test';
		$result = $class::addPathElement($dir,$element);
		$this->assertSame($dir.'/'.$element, $result);
		
		$dir = 'unixRelativePath/test/test/';
		$result = $class::addPathElement($dir,$element);
		$this->assertSame($dir.$element, $result);
    }

    /**
     * @covers XoopsFolderHandler::inXoopsPath
     * @todo   Implement testInXoopsPath().
     */
    public function testInXoopsPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::inPath
     * @todo   Implement testInPath().
     */
    public function testInPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::chmod
     * @todo   Implement testChmod().
     */
    public function testChmod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::tree
     * @todo   Implement testTree().
     */
    public function testTree()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::dirsize
     * @todo   Implement testDirsize().
     */
    public function testDirsize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::copy
     * @todo   Implement testCopy().
     */
    public function testCopy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::move
     * @todo   Implement testMove().
     */
    public function testMove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::messages
     * @todo   Implement testMessages().
     */
    public function testMessages()
    {
		$dir = dirname(__FILE__);
		$instance = new $this->myClass($dir, false, false);
		$this->assertTrue(file_exists($dir));
		
		$result = $instance->messages();
		$this->assertTrue(is_array($result));
    }

    /**
     * @covers XoopsFolderHandler::errors
     * @todo   Implement testErrors().
     */
    public function testErrors()
    {
		$dir = dirname(__FILE__);
		$instance = new $this->myClass($dir, false, false);
		$this->assertTrue(file_exists($dir));
		
		$result = $instance->errors();
		$this->assertFalse($result);
    }

    /**
     * @covers XoopsFolderHandler::realpath
     * @todo   Implement testRealpath().
     */
    public function testRealpath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XoopsFolderHandler::isSlashTerm
     * @todo   Implement testIsSlashTerm().
     */
    public function testIsSlashTerm()
    {
		$class = $this->myClass;
		$dir = 'dir\\';
		$result = $class::isSlashTerm($dir);
		$this->assertTrue($result);
		
		$dir = 'dir/';
		$result = $class::isSlashTerm($dir);
		$this->assertTrue($result);
		
		$dir = 'dir';
		$result = $class::isSlashTerm($dir);
		$this->assertFalse($result);
    }
}
