<?php
namespace Xmf;

require_once(__DIR__.'/../../init_mini.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-22 at 19:56:36.
 */
 
/**
* PHPUnit special settings :
* @backupGlobals disabled
* @backupStaticAttributes disabled
*/

class MetagenTest extends \MY_UnitTestCase
{
    /**
     * @var Metagen
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Metagen;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xmf\Metagen::assignTitle
     * @todo   Implement testAssignTitle().
     */
    public function testAssignTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Metagen::assignKeywords
     * @todo   Implement testAssignKeywords().
     */
    public function testAssignKeywords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Metagen::assignDescription
     * @todo   Implement testAssignDescription().
     */
    public function testAssignDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Metagen::generateKeywords
     * @todo   Implement testGenerateKeywords().
     */
    public function testGenerateKeywords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Metagen::generateDescription
     * @todo   Implement testGenerateDescription().
     */
    public function testGenerateDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Metagen::generateMetaTags
     * @todo   Implement testGenerateMetaTags().
     */
    public function testGenerateMetaTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Metagen::generateSeoTitle
     * @todo   Implement testGenerateSeoTitle().
     */
    public function testGenerateSeoTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
