<?php
namespace Xmf;

require_once(dirname(__FILE__).'/../../init_mini.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-22 at 19:56:36.
 */
 
/**
* PHPUnit special settings :
* @backupGlobals disabled
* @backupStaticAttributes disabled
*/

class YamlTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Yaml
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Yaml;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * class is empty extension for compatibility, just make sure methods are available
     *
     * @covers Xmf\Yaml::dump
     */
    public function testDump()
    {
        $this->assertTrue(method_exists('Xmf\Yaml', 'dump'));
        $this->assertTrue(is_callable(array('Xmf\Yaml', 'dump')));
    }

    /**
     * @covers Xmf\Yaml::load
     */
    public function testLoad()
    {
        $this->assertTrue(method_exists('Xmf\Yaml', 'load'));
        $this->assertTrue(is_callable(array('Xmf\Yaml', 'load')));
    }

    /**
     * @covers Xmf\Yaml::save
     */
    public function testSave()
    {
        $this->assertTrue(method_exists('Xmf\Yaml', 'save'));
        $this->assertTrue(is_callable(array('Xmf\Yaml', 'save')));
    }

    /**
     * @covers Xmf\Yaml::read
     */
    public function testRead()
    {
        $this->assertTrue(method_exists('Xmf\Yaml', 'read'));
        $this->assertTrue(is_callable(array('Xmf\Yaml', 'read')));
    }
}
