<?php
namespace Xmf\Module;

require_once(dirname(__FILE__).'/../../../init_new.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-22 at 19:56:36.
 */
 
/**
 * PHPUnit special settings :
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */

class AdminTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Admin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Admin::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xmf\Module\Admin::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::is26
     * @todo   Implement testIs26().
     */
    public function testIs26()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::menuIconPath
     * @todo   Implement testMenuIconPath().
     */
    public function testMenuIconPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::addConfigBoxLine
     * @todo   Implement testAddConfigBoxLine().
     */
    public function testAddConfigBoxLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::addInfoBox
     * @todo   Implement testAddInfoBox().
     */
    public function testAddInfoBox()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::addInfoBoxLine
     * @todo   Implement testAddInfoBoxLine().
     */
    public function testAddInfoBoxLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::addItemButton
     * @todo   Implement testAddItemButton().
     */
    public function testAddItemButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::renderButton
     * @todo   Implement testRenderButton().
     */
    public function testRenderButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::displayButton
     * @todo   Implement testDisplayButton().
     */
    public function testDisplayButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::renderInfoBox
     * @todo   Implement testRenderInfoBox().
     */
    public function testRenderInfoBox()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::displayInfoBox
     * @todo   Implement testDisplayInfoBox().
     */
    public function testDisplayInfoBox()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::renderIndex
     * @todo   Implement testRenderIndex().
     */
    public function testRenderIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::displayIndex
     * @todo   Implement testDisplayIndex().
     */
    public function testDisplayIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::displayNavigation
     * @todo   Implement testDisplayNavigation().
     */
    public function testDisplayNavigation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::renderAbout
     * @todo   Implement testRenderAbout().
     */
    public function testRenderAbout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::setPaypal
     * @todo   Implement testSetPaypal().
     */
    public function testSetPaypal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::displayAbout
     * @todo   Implement testDisplayAbout().
     */
    public function testDisplayAbout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::addConfigError
     * @todo   Implement testAddConfigError().
     */
    public function testAddConfigError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::addConfigAccept
     * @todo   Implement testAddConfigAccept().
     */
    public function testAddConfigAccept()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::iconUrl
     * @todo   Implement testIconUrl().
     */
    public function testIconUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xmf\Module\Admin::checkModuleVersion
     * @todo   Implement testCheckModuleVersion().
     */
    public function testCheckModuleVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
